sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.069.0-rc1
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.16.1
 - ldc-0.15.1
 - gdc-4.9.2
 - gdc-5.2.0

matrix:
  allow_failures:
   - os: osx
     d: gdc-4.9.2
   - os: osx
     d: gdc-5.2.0
  env:
   - ARCH=x86
   - ARCH=x86_64

addons:
  apt:
    packages:
     - python3
     - python
     - python3-nose
     - python-nose
     - python3-numpy
     - python-numpy
     - python-dev
     - python3-dev

install:
    - python3 setup.py install --user

script: 
    - python3 runtests.py --compiler=$DC runtests:test_hello
      runtests:test_many_libs
      runtests:test_arraytest
      runtests:test_inherit
      runtests:test_rawexample
      runtests:test_testdll
      runtests:test_d_and_c
      runtests:test_multithreading
      runtests:PydUnittests.test_class_wrap
      runtests:PydUnittests.test_def
      runtests:PydUnittests.test_embedded
      runtests:PydUnittests.test_make_object
      runtests:PydUnittests.test_pydobject
      runtests:PydUnittests.test_struct_wrap
      runtests:PydUnittests.test_const
      runtests:PydUnittests.test_typeinfo
      runtests:PydUnittests.test_func_wrap
      runtests:PydUnittests.test_extra
      runtests:PydUnittests.test_thread
      runtests:DeimosUnittests.test_link
      runtests:DeimosUnittests.test_object
      runtests:DeimosUnittests.test_datetime
      runtests:test_pyind
      runtests:test_simple_embedded
      runtests:test_interpcontext
      runtests:test_def
      runtests:test_pydobject
